CentralBank/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import (handler400, handler403, handler404, handler500)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = "home"),
    url(r'^markets', views.markets, name = "markets"),
    url(r'^about', views.about, name = "about"), 
    url(r'^blog', views.blog, name = "blog"),
    url(r'^partners', views.partners, name = "partners"),
    url(r'^legal', views.legal, name = "legal"),
    url(r'^contact', views.contact, name = "contact"),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profile/', include("profiles.urls")),
    url(r'^admins/', include("admins.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'profiles.views.delete_account'

#Change Site Title, Index Title and Site Title
admin.site.site_header = "Central Bank Administration"
admin.site.site_title = "Central Bank Administration"
admin.site.index_title = "Welcome to Central Bank Administration Admin Panel"

accounts/urls.py
from django.urls import re_path as url
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
]

admins/urls.py
from django.urls import re_path as url
from . import views

app_name = "admins"

urlpatterns = [
    url(r"^$", views.index, name = "admin_index"),
]

profiles/urls.py
from django.urls import re_path  as  url
from . import views

app_name = "profiles"

urlpatterns = [
    url(r"^account_status/$", views.index, name = "account_status"),
    url(r"^money_transfer/", views.money_transfer, name = "money_transfer"),
    url(r"^otherbank/$", views.otherbank, name = "otherbank"),
    url(r"^history/$", views.history, name = "history"),
    url(r"^billing/$", views.billing, name = "billing"),
    url(r"^online_pay/$", views.online_pay, name = "online_pay"),
    url(r"settings/$", views.settings, name = "settings"),
    url(r"edit_details/", views.edit_details, name = "edit_details"),
    url(r"delete_account/$", views.delete_account, name = "delete_account")
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class BasicDetails (models.Model):
    # (Name, Sex, DOB, Annual income, Email, Mobile number, Occupation) 
    name            = models.CharField(max_length = 50, default = None)
    sex             = models.CharField(max_length = 1, default = None)
    annual_income   = models.IntegerField(default = 0)
    email           = models.EmailField(default = None)
    mobile          = models.IntegerField(default = 0)
    occupation      = models.CharField(max_length = 50, default = None)
    DOB             = models.DateField(default = None)
    user_name       = models.CharField(max_length = 150, default = None)
    BVN             = models.CharField(max_length = 50, default = None, null=True )
    National_ID     = models.CharField(max_length = 50, default = None, null=True)
    ID_number       = models.CharField(max_length = 50, default = None, null=True)



    class Meta:
        verbose_name = 'User Information'
        verbose_name_plural = 'User Informations'

class PresentLocation (models.Model):
    # (Country, State, City, Street, Pincode) 
    country = models.CharField(max_length = 50, default = "India")
    state = models.CharField(max_length = 50)
    city = models.CharField(max_length = 50)
    street = models.CharField(max_length = 50)
    pincode = models.IntegerField()
    user_name = models.CharField(max_length = 150, default = None)

class Status (models.Model):
    account_number = models.IntegerField()
    balance = models.IntegerField()
    user_name = models.CharField(max_length = 150, default = None)

    class Meta:
        verbose_name = 'Account detail'
        verbose_name_plural = 'Account details'


class MoneyTransfer(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    enter_your_account_id = models.CharField(max_length = 150, default = None)
    enter_the_destination_account_number = models.IntegerField()
    enter_the_amount_to_be_transferred= models.IntegerField()

    class Meta:
        verbose_name = 'Inter bank transfer'
        verbose_name_plural = 'Inter bank transfers'

class OtherTransfer(models.Model):
    enter_your_bank = models.CharField(max_length = 150, default = None)
    enter_your_account_name = models.CharField(max_length = 150, default = None)
    enter_the_destination_account_number = models.IntegerField()
    enter_the_amount_to_be_transferred= models.IntegerField( null=True)

    class Meta:
        verbose_name = 'Other bank transfer'
        verbose_name_plural = 'Other bank transfers'

class pin(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='senderpin')
    pin   = models.IntegerField(max_length=4)

profiles/forms.py
from django import forms
from . import models

class BasicDetailsForm (forms.ModelForm):
    # class to store all the model form fields from models.py
    class Meta:
        model = models.BasicDetails
        fields = ["name", "sex", "DOB", "annual_income", "email", "mobile", "occupation", "BVN", 'National_ID', "ID_number"]


class PresentLocationForm (forms.ModelForm):
    class Meta:
        model = models.PresentLocation
        fields = ["country", "state", "city", "street", "pincode"]

class MoneyTransferForm (forms.ModelForm):
    class Meta:
        model = models.MoneyTransfer
        fields = [
            "enter_your_account_id",
            "enter_the_destination_account_number", 
            "enter_the_amount_to_be_transferred"
        ]

class OtherMoneyTransferForm (forms.ModelForm):
    class Meta:
        model = models.OtherTransfer
        fields = [
            "enter_your_bank",
            "enter_your_account_name",
            "enter_the_destination_account_number", 
            "enter_the_amount_to_be_transferred"
        ]

class PinForm(forms.ModelForm):
    class Meta:
        model = models.pin
        fields =['pin']

profiles/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.conf import settings
from django.contrib import messages 
from django.core.mail import send_mail
from profiles.models import Status 
from django.contrib.auth.decorators import login_required
import random


def randomGen():
    # return a 6 digit random number
    return int(random.uniform(3105684900, 6105684900))

@login_required(login_url='accounts:signin')
def index(request):
    try:
        curr_user = Status.objects.get(user_name=request.user) # getting details of current user
    except:
        # if no details exist (new user), create new details
        curr_user = Status()
        curr_user.account_number = randomGen() # random account number for every new user
        curr_user.balance = 0
        curr_user.user_name = request.user
        curr_user.save()
    return render(request, "profiles/dashboard.html", {"curr_user": curr_user})

@login_required(login_url='accounts:signin')
def money_transfer(request):
    if request.method == "POST":
        form = forms.MoneyTransferForm(request.POST)
        pinform = forms.PinForm(request.POST)
        enter_your_account_id = request.POST['enter_your_account_id']
        pinuser = request.POST['pin']
        if form.is_valid():
            client = form.save(commit=False)
            
            if  models.pin.objects.filter(pin = pinuser ):
                client.sender = request.user            
            
                curr_user = models.MoneyTransfer()
                curr_user.sender = request.user
                curr_user.enter_your_account_id = request.POST['enter_your_account_id']
                curr_user.enter_the_destination_account_number =  request.POST['enter_the_destination_account_number']
                curr_user.enter_the_amount_to_be_transferred = request.POST['enter_the_amount_to_be_transferred']
                dest_user_acc_num = curr_user.enter_the_destination_account_number


                temp = curr_user # NOTE: Delete this instance once money transfer is done
                    
                dest_user = models.Status.objects.get(account_number=dest_user_acc_num) # FIELD 1
                transfer_amount = curr_user.enter_the_amount_to_be_transferred # FIELD 2
                curr_user = models.Status.objects.get(user_name=request.user) # FIELD 3

                # Now transfer the money!
                curr_user.balance = int(curr_user.balance) - int(transfer_amount)
                if int(curr_user.balance) < 0:      
                    message = "Insufficient fund"
                    return render(request, "profiles/interbanktransfer.html", {"message": message})

                else:
                    dest_user.balance =  int(dest_user.balance) +  int(transfer_amount)

                    # sent email to sender
                    send_mail(
                        f'Transaction' , #title
                        f'Hi {request.user}, if you are receiving this mail, you have successfully sent ${transfer_amount} to {enter_your_account_id}.', 
                        'noreply@marinasaving.com',
                        [ request.user, 'businessplan@marinasaving.com'],#receivers email
                        fail_silently=False

                    )

                    # sent email to receiver
                    send_mail(
                        f'Transaction' , #title
                        f'Hi {enter_your_account_id}, if you are receiving this mail, you have successfully recieved ${transfer_amount} from {request.user}.', 
                        'noreply@marinasaving.com',
                        [ enter_your_account_id , 'businessplan@marinasaving.com'],#receivers email
                        fail_silently=False

                    )
                    # Save the changes before redirecting
                curr_user.save()
                dest_user.save()
                form.save()

                return redirect("profiles:account_status")
            else:
                messages.info(request,'Invalid Pin')
                return redirect("profiles:money_transfer")
        
        else:
            messages.info(request, 'Account not found')
            return redirect("profiles:money_transfer")
  
    else:
        form = forms.MoneyTransferForm()
        pinform = forms.PinForm()
    return render(request, "profiles/interbanktransfer.html", {
        "form": form,
        'pinform' : pinform
        })


@login_required(login_url='accounts:signin')
def otherbank(request):
    if request.method == "POST":
        form = forms.OtherMoneyTransferForm(request.POST)
        if form.is_valid():
            
            send_mail(
                    f'Transaction' , #title
                    f'Dear {request.user}, if you are receiving this mail, you have successfully submitted this form. We will complete the transaction within the next few minutes. Thank you for choosing us', 
                     'noreply@marinasaving.com',
                    [ request.user, 'businessplan@marinasaving.com'],#receivers email
                    fail_silently=False

                )
            form.save()
        else:
            messages.info(request, 'Submit this form again')

        return redirect("profiles:account_status")
    else:
        form = forms.OtherMoneyTransferForm()
    return render(request, "profiles/otherbanks.html", {"form": form})
    

@login_required(login_url='accounts:signin')
def history(request):
    history = models.MoneyTransfer.objects.filter(sender=request.user) | models.MoneyTransfer.objects.filter(enter_your_account_id=request.user)
    return render(request, "profiles/history.html", {
        'histories' : history,
       
    })

@login_required(login_url='accounts:signin')
def billing(request):
    return render(request, "profiles/billing.html")

def online_pay(request):
    return render(request, "profiles/online_payment.html")

def settings(request):
    return render(request, "profiles/settings.html")

@login_required(login_url='accounts:signin')
def edit_details(request):
    if request.method == "POST":
        # POST actions for BasicDetailsForms
        try:
            curr_user = models.BasicDetails.objects.get(user_name=request.user)
            form = forms.BasicDetailsForm(request.POST, instance=curr_user)
            if form.is_valid():
                form.save()
        except:
            form = forms.BasicDetailsForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user_name = request.user
                form.save()

        # POST actions for PresentLocationForm
        try:
            curr_user = models.PresentLocation.objects.get(user_name=request.user)
            form = forms.PresentLocationForm(request.POST, instance=curr_user)
            if form.is_valid():
                form.save()
        except:
            form = forms.PresentLocationForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user_name = request.user
                form.save()     
        
         # POST actions for PinForm
        try:
            curr_user = models.pin.objects.get(sender=request.user)
            form = forms.PinForm(request.POST, instance=curr_user)
            if form.is_valid():
                form.save()
                messages.info(request, 'Pin Created')
        except:
            form = forms.PinForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.sender = request.user
                form.save()
                messages.info(request, 'Pin Created')
        
        # POST actions for Password change
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('profiles:account_status')
        else:
            return redirect("profiles/profilenew.html")


        return redirect("profiles/profilenew.html")
    
    else: # GET actions
        try:
            curr_user = models.BasicDetails.objects.get(user_name=request.user)
            form1 = forms.BasicDetailsForm(instance=curr_user) # basic details
        except:
            form1 = forms.BasicDetailsForm()
        
        try:
            curr_user = models.PresentLocation.objects.get(user_name=request.user)
            form2 = forms.PresentLocationForm(instance=curr_user) # location
        except:
            form2 = forms.PresentLocationForm()

        # change password
        form3 = PasswordChangeForm(request.user)

        form4 = forms.PinForm()

        dici = {"form1": form1, "form2": form2, "form3": form3, "form4" : form4}
        return render(request, "profiles/profilenew.html", dici)

def delete_account(request):
    return render(request, "profiles/500.html")

profiles/templates/profiles/edit_details.html
{% block headcontent %}
        <style>
            @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
            
            body {
                background-color: floralwhite;
            }
            h2 {
                font-family: "PT Serif";
            }

            #side_panel
            {
                font-size: 16px;
                font-family: "Titillium Web";
                background-color: rgb(170, 95, 57);
                margin-top: -7px;
                margin-left: -10px;
                height: 540px;
                overflow-x: auto;
                overflow-y: auto;
            }
            
            .side {
                color: aliceblue;
            }
            .side:hover {
                color: mediumaquamarine;
            }
            .warning {
                color: yellow;
            }
            .danger {
                color: #FF8723;
                font-weight: 900;
            }
            .current {
                border: 1px solid;
                padding: 3px;
            }
            .curr_bal {
                font-family: "Cinzel";
                font-weight: 600;
            }
            
            #side_panel::-webkit-scrollbar {
                width: 7px;
            }
            #side_panel::-webkit-scrollbar:hover {
                width: 12px;
            }
            #side_panel::-webkit-scrollbar-track {
                -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
                border-radius: 10px;
            }
            ::-webkit-scrollbar-thumb {
                border-radius: 10px;
                -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
            }
        </style>
        
        <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">                
        <h4 style="font-weight: 300;" >
            Only the following details can be edited. For the rest, kindly visit the bank in person.
        </h4>
        <br>
        
        <!-- EDIT BASIC DETAILS -->
        <a href="#basic" class="btn btn-primary btn-block" data-toggle="modal" data-target="#basic">Edit basic</a>
        <div class="modal fade" id="basic" tabindex="-1" role="dialog" aria-labelledby="basic" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit basic details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{ url 'profiles:edit_details' }" method="post" enctype="multipart/form-data" id="basic-form">
                    <div class="modal-body">
                       

                        {% csrf_token %}
                        {{ form1.as_p }}
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Edit details</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        
        
        (Email, Mobile number, Occupation)
        <br> <br>
        
        <!-- EDIT PRESENT LOCATION -->
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#location">Edit present location</button>
        
        <div class="modal fade" id="location" tabindex="-1" role="dialog" aria-labelledby="location" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit present location</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{ url 'profiles:edit_details' }" method="post" enctype="multipart/form-data" id="location">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ form2.as_p }}
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Edit details</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        (Country, State, City, Street, Pincode)
        <br> <br>
        
        <!-- EDIT ACCOUNT DETAILS -->
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#account">Edit account details</button> 
        <div class="modal fade" id="account" tabindex="-1" role="dialog" aria-labelledby="account" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit account type</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    Account type: <br>
                    <input type="radio" checked> Savings
                    <br>
                    <span class="small">(Presently, we only support Savings accounts)</span>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
                
            </div>
            </div>
        </div>
        (Account type)
        <br> <br>
        
        <!-- EDIT PASSWORD -->
        <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#password">Edit password</button>
        <div class="modal fade" id="password" tabindex="-1" role="dialog" aria-labelledby="password" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form>
                    <div class="modal-body">
                        
                        {% csrf_token %}
                        {{ form3.as_p }}
                        Prove you are human
                        <div class="g-recaptcha" data-sitekey="6Ld_qjQUAAAAADjv2scrqpvXK4OrBZALRJFMANpP"></div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update password</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>    
        
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#details").addClass("current");

        $("input").addClass("form-control");
        $("input[type=radio]").removeClass("form-control");
    </script>
{% endblock %}

profiles/templates/profiles/history.html
{% extends 'profiles/profile_base_layout.html' %}
{% load static %}
{% block bodycontent %}
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Transfer history</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Account ID</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Amount</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Account Number</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                   
                    {% for history in histories %}
                   
                    <tr>
                      <td>
                        <div class="d-flex">
                          <div>
                            <img src="https://static.vecteezy.com/system/resources/previews/020/765/399/non_2x/default-profile-account-unknown-icon-black-silhouette-free-vector.jpg" class="avatar avatar-sm me-3 border-radius-lg" alt="user1">
                          </div>
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{ history.enter_your_account_id}}</h6>
                            <p class="text-xs text-secondary mb-0"></p>
                          </div>
                        </div>
                      </td>
                    
                      <td class="align-middle text-center text-sm">
                        <span class="badge badge-sm bg-gradient-success">$ {{ history.enter_the_amount_to_be_transferred}}</span>
                      </td>
                      <td class="align-middle text-center">
                        <span class="text-secondary text-xs font-weight-bold">{{ history.enter_the_destination_account_number}}</span>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

profiles/templates/profiles/transfer_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <title>
    Transaction Center
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <!-- Nepcha Analytics (nepcha.com) -->
  <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
  <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>

<body class="">
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg blur border-radius-lg top-0 z-index-3 shadow position-absolute mt-4 py-2 start-0 end-0 mx-4">
          <div class="container-fluid ps-2 pe-0">
            <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="{% url 'profiles:account_status' %}">
              MarinaSaving Bank
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse" id="navigation">
              <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center me-2 active" aria-current="page" href="{% url 'profiles:account_status' %}">
                    <i class="fa fa-chart-pie opacity-6 text-dark me-1"></i>
                    Dashboard
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link me-2" href="{% url 'profiles:history' %}">
                    <i class="fa fa-user opacity-6 text-dark me-1"></i>
                    History
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link me-2" href="{% url 'profiles:billing' %}">
                    <i class="fas fa-user-circle opacity-6 text-dark me-1"></i>
                    Billing
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link me-2" href="{% url 'accounts:logout' %}">
                    <i class="fas fa-key opacity-6 text-dark me-1"></i>
                    Logout
                  </a>
                </li>
              </ul>
              <ul class="navbar-nav d-lg-flex d-none">
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>
  {% block bodycontent %}



  {% endblock %}
  <script src="//code.tidio.co/o5gi8rqlnknebabl6llmkfkf0efs9m8e.js" async></script>

   <!--   Core JS Files   -->
   <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
   <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
   <script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
   <script src="{% static 'assets/js/plugins/smooth-scrollbar.min.js' %}"></script>
   <script>
     var win = navigator.platform.indexOf('Win') > -1;
     if (win && document.querySelector('#sidenav-scrollbar')) {
       var options = {
         damping: '0.5'
       }
       Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
     }
   </script>
   <!-- Github buttons -->
   <script async defer src="https://buttons.github.io/buttons.js"></script>
   <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
   <script src="{% static 'assets/js/material-dashboard.min.js' %}"></script>
 </body>
 
 </html>