CentralBank/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import (handler400, handler403, handler404, handler500)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = "home"),
    url(r'^markets', views.markets, name = "markets"),
    url(r'^about', views.about, name = "about"), 
    url(r'^blog', views.blog, name = "blog"),
    url(r'^partners', views.partners, name = "partners"),
    url(r'^legal', views.legal, name = "legal"),
    url(r'^contact', views.contact, name = "contact"),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profile/', include("profiles.urls")),
    url(r'^admins/', include("admins.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'profiles.views.delete_account'

#Change Site Title, Index Title and Site Title
admin.site.site_header = "Central Bank Administration"
admin.site.site_title = "Central Bank Administration"
admin.site.index_title = "Welcome to Central Bank Administration Admin Panel"

accounts/urls.py
from django.urls import re_path as url
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
]

admins/urls.py
from django.urls import re_path as url
from . import views

app_name = "admins"

urlpatterns = [
    url(r"^$", views.index, name = "admin_index"),
]

templates/about.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
About our banking
{% endblock %}

{% block bodycontent%}
	<main>
		<!-- section content begin -->
		<div class="uk-section">
			<div class="uk-container">
				<div class="uk-grid">
					<div class="uk-width-1-1 uk-flex uk-flex-center">
						<div class="uk-width-3-4@m uk-text-center">
							<h1 class="uk-margin-small-bottom">Putting our clients first since 1998</h1>
							<p class="uk-text-lead uk-text-muted uk-margin-remove-top">For nearly 30 years, we’ve been empowering clients by helping them take control of their financial lives.</p>
						</div>
					</div>
					<div class="uk-grid uk-grid-large uk-child-width-1-3@m uk-margin-medium-top" data-uk-grid>
						<div class="uk-flex uk-flex-left">
							<div class="uk-margin-right">
								<div class="in-icon-wrap circle primary-color">
									<i class="fas fa-leaf fa-lg"></i>
								</div>
							</div>
							<div>
								<h3>Philosophy</h3>
								<p class="uk-margin-remove-bottom">FCs look for a competitive advantage in the market. They want their portfolio companies to be able to generate sales and profits before competitors enter the market and reduce profitability. The fewer direct competitors operating in the space, the better.</p>
							</div>
						</div>
						<div class="uk-flex uk-flex-left">
							<div class="uk-margin-right">
								<div class="in-icon-wrap circle primary-color">
									<i class="fas fa-hourglass-end fa-lg"></i>
								</div>
							</div>
							<div>
								<h3>History</h3>
								<p class="uk-margin-remove-bottom">Venture Capital started as an entrepreneurial venture. The founding editors, Colin 
									Mason and Richard Harrison, noted that the initial idea to launch a journal was 
									serendipitous (Harrison and Mason 2019). The increasing economic significance venture capital as an alternative investment in the 1990s led Colin and Richard to create 
									a new journal to publish papers on entrepreneurial finance to stimulate and provide 
									an outlet for publishing research on venture capital and private equity, corporate 
									venturing, business angel investing and public sector venture capital. They rightly 
									recognized the need for a journal that would raise the profile of entrepreneurial 
									finance, stimulate research into entrepreneurial finance and provide a focus for the 
									publication of papers from a diverse range of perspectives, thereby overcoming the 
									disciplinary, theoretical and methodological fragmentation of the field at that time 
									(Mason and Harrison 1999)</p>
									<a href="https://www.tandfonline.com/doi/pdf/10.1080/13691066.2021.1886660">Read more</a>	
							</div>
						</div>
						<div class="uk-flex uk-flex-left">
							<div class="uk-margin-right">
								<div class="in-icon-wrap circle primary-color">
									<i class="fas fa-flag fa-lg"></i>
								</div>
							</div>
							<div>
								<h3>Culture</h3>
								<p class="uk-margin-remove-bottom">In 2020, venture capital (VC) firms and investors were hit by some of the most substantial and unprecedented changes they’ve had to contend with yet: widespread market uncertainty, fewer funding rounds and less face-to-face interaction with clients. The sum of all these conditions could have made quality investment difficult or even impracticable, yet digital technology and culture change have proven, once again, that the restrictions of yesteryear need not interrupt modern business.

									Still, the challenge has been omnipresent and a generally conservative attitude to unique business ventures took hold. McKinsey & Co recorded a significant drop in overall executive commitment towards innovation at the height of the crisis (23 percentage points (pp), down 32pp from its pre-crisis level of 55pp), a reduction that it doesn’t expect to fully recover until after pandemic conditions have fully dissipated. Furthermore, when the article was originally published in June 2020, 90% of surveyed executives predicted that COVID-19 would change business norms significantly for the next five years. Although it’s still too early to tell the long-term effects, the short-term implications of this prediction couldn’t ring more true. </p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- section content end -->
		<!-- section content begin -->
		<div class="uk-section in-offset-top-20 in-offset-bottom-20">
			<div class="uk-container">
				<div class="uk-grid">
					<div class="uk-width-1-1">
						<div class="uk-card uk-card-default uk-border-rounded uk-background-center uk-background-contain uk-background-image@m" style="background-image: url(img/blockit/in-team-background-1.png);" data-uk-parallax="bgy: -100">
							<div class="uk-card-body">
								<div class="uk-grid uk-flex uk-flex-center">
									<div class="uk-width-3-4@m uk-text-center">
										<h2>Trust the Professionals</h2>
										<p>We are a group of passionate, independent thinkers who never stop exploring new ways to improve trading for the self-directed investor.</p>
									</div>
								</div>
								<div class="uk-grid uk-child-width-1-2@m uk-margin-medium-top" data-uk-grid="">
									<div class="uk-flex uk-flex-left uk-first-column">
										<div class="uk-margin-right">
											<img class="uk-align-center " src="{% static 'home/img/blockit/in-team-1.png' %}" alt="image-team" width="300">
										</div>
										<div>
											<p class="uk-text-small uk-text-muted uk-text-uppercase uk-margin-remove-bottom">Chief Executive Officer</p>
											<h4 class="uk-margin-small-top">Cynthia Dixon</h4>
											<p>Nostrum exercitationem ullam corporis suscipit labor samnisi ute aliquid fugiat.</p>
											<div>
												<a class="uk-link-muted" href="#"><i class="fab fa-facebook-f uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-twitter uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-linkedin-in"></i></a>
											</div>
										</div>
									</div>
									<div class="uk-flex uk-flex-left">
										<div class="uk-margin-right">
											<img class="uk-align-center " src="{% static 'home/img/blockit/in-team-2.png' %}" alt="image-team" width="300">
										</div>
										<div>
											<p class="uk-text-small uk-text-muted uk-text-uppercase uk-margin-remove-bottom">Executive Assistant</p>
											<h4 class="uk-margin-small-top">Arthur Parker</h4>
											<p>Nostrum exercitationem ullam corporis suscipit labor samnisi ute aliquid fugiat.</p>
											<div>
												<a class="uk-link-muted" href="#"><i class="fab fa-facebook-f uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-twitter uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-linkedin-in"></i></a>
											</div>
										</div>
									</div>
									<div class="uk-flex uk-flex-left uk-grid-margin uk-first-column">
										<div class="uk-margin-right">
											<img class="uk-align-center " src="https://th.bing.com/th/id/OIP.jJBW_GFOtPY5WX_dMITEHQAAAA?pid=ImgDet&rs=1" alt="image-team" width="300">
										</div>
										<div>
											<p class="uk-text-small uk-text-muted uk-text-uppercase uk-margin-remove-bottom">Major Investor</p>
											<h4 class="uk-margin-small-top">Ma Huateng</h4>
											<p>Chairman And CEO,   Tencent  Holdings.</p>
											<div>
												<a class="uk-link-muted" href="#"><i class="fab fa-facebook-f uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-twitter uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-linkedin-in"></i></a>
											</div>
										</div>
									</div>
									<div class="uk-flex uk-flex-left uk-grid-margin">
										<div class="uk-margin-right">
											<img class="uk-align-center " src="https://assets-us-01.kc-usercontent.com/5cb25086-82d2-4c89-94f0-8450813a0fd3/53bd4d87-ccf5-445e-9463-e35e59c2a19f/elon_musk.jpg?fm=jpg&auto=format" alt="image-team" width="300">
										</div>
										<div>
											<p class="uk-text-small uk-text-muted uk-text-uppercase uk-margin-remove-bottom">Major Investor</p>
											<h4 class="uk-margin-small-top">Elon Musk</h4>
											<p>CEO, Tesla, SpaceX.</p>
											<div>
												<a class="uk-link-muted" href="#"><i class="fab fa-facebook-f uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-twitter uk-margin-small-right"></i></a>
												<a class="uk-link-muted" href="#"><i class="fab fa-linkedin-in"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- section content end -->
		<!-- section content begin -->
		<div class="uk-section">
			<div class="uk-container">
				<div class="uk-grid uk-flex uk-flex-center">
					<div class="uk-width-3-4@m">
						<div class="uk-grid uk-flex uk-flex-middle" data-uk-grid>
							<div class="uk-width-1-2@m">
								<h4 class="uk-text-muted in-offset-bottom-10">Number speaks</h4>
								<h1 class="uk-margin-medium-bottom">We always ready<br>for a challenge.</h1>
							</div>
							<div class="uk-width-1-2@m">
								<div class="uk-margin-large" data-uk-grid>
									<div class="uk-width-1-3@m">
										<h1 class="uk-text-primary uk-text-right@m">
											<span class="count" data-counter-end="213">0</span>
										</h1>
										<hr class="uk-divider-small uk-text-right@m">
									</div>
									<div class="uk-width-expand@m">
										<h3>Trading instruments</h3>
										<p>Reprehenderit qui in svoluptate velit esse quam molestiae vel illum qui dolorem fugiat quo.</p>
									</div>
								</div>
								<div class="uk-margin-large" data-uk-grid>
									<div class="uk-width-1-3@m">
										<h1 class="uk-text-primary uk-text-right@m">
											<span class="count" data-counter-end="32">0</span>
										</h1>
										<hr class="uk-divider-small uk-text-right@m">
									</div>
									<div class="uk-width-expand@m">
										<h3>Countries covered</h3>
										<p>At vero deleniti eto accusamus blanditiis praesentium voluta iusto dignissimos ducimus.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- section content end -->
	</main>
	{% endblock %}

templates/base_layout.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<!-- meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="marinasaving Bank official website">
	<meta name="keywords" content="marinasaving Bank official website, trading, investing">
	<meta name="author" content="marinasaving Bank official website">
	<meta name="theme-color" content="#00B276">
	<!-- preload assets -->
	<link rel="preload" href="{% static 'home/fonts/fa-brands-400.woff2' %}" as="font" type="font/woff2" crossorigin>
	<link rel="preload" href="{% static 'home/fonts/fa-solid-900.woff2' %}" as="font" type="font/woff2" crossorigin>
	<link rel="preload" href="{% static 'home/fonts/mulish-v3-latin-300.woff2' %}" as="font" type="font/woff2" crossorigin>
	<link rel="preload" href="{% static 'home/fonts/mulish-v3-latin-800.woff2' %}" as="font" type="font/woff2" crossorigin>
	<link rel="preload" href="{% static 'home/fonts/roboto-v20-latin-300.woff2' %}" as="font" type="font/woff2" crossorigin>
	<link rel="preload" href="{% static 'home/css/style.css' %}" as="style">
	<link rel="preload" href="{% static 'home/js/vendors/uikit.min.js' %}" as="script">
	<link rel="preload" href="{% static 'home/js/utilities.min.js' %}" as="script">
	<link rel="preload" href="{% static 'home/js/config-theme.js' %}" as="script">
	<!-- stylesheet -->
	<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
	<!-- uikit -->
	<script src="{% static 'home/js/vendors/uikit.min.js' %}"></script>
	<!-- favicon -->
	<link rel="shortcut icon" href="{% static 'home/img/favicon.ico' %}" type="image/x-icon">
	<!-- touch icon -->
	<link rel="apple-touch-icon-precomposed" href="{% static 'home/img/apple-touch-icon.png' %}">
	  {% block style%}

	  {% endblock %}
	
	<title>
		{% block title %}

		{% endblock %} 
	</title>
</head>

<body>
	<!-- page loader begin -->
	<div class="page-loader">
		<div></div>
		<div></div>
		<div></div>
	</div>
	<!-- page loader end -->
	<!-- header begin -->
	<header>
		<div class="uk-section uk-section-default uk-padding-remove-vertical uk-background-contain uk-background-top-left" style="background-image: url({% static 'home/img/in-header-background.png' );">
			<div class="uk-container">
				<div class="uk-child-width-1-2@s in-top-header" data-uk-grid>
					<div class="uk-flex uk-flex-center uk-flex-left@s">
						<a class="uk-logo" href="{% url 'home' %}">
							<img src="{% static 'home/img/in-lazy.gif' %}" data-src="{% static 'home/img/user/header-logo-7QJKXa.svg' %}" alt="logo" width="130" height="36" data-uk-img>
						</a>
					</div>
					<div class="uk-grid-collapse uk-flex uk-flex-middle uk-flex-right uk-visible@s" data-uk-grid>
						<div class="uk-margin-right in-language-select uk-visible@m">
							<button class="uk-button uk-button-link" type="button"><i class="fas fa-globe"></i>English</button>
							<div class="uk-box-shadow-medium" data-uk-dropdown="mode: click; offset: 16; pos: bottom-right; boundary: !.in-language-select; animation: uk-animation-slide-top-small; duration: 300">
								<ul class="uk-nav uk-dropdown-nav">
									<li><a href="#"><img src="{% static 'home/img/in-lazy.gif' %}" data-src="{% static 'home/img/in-flag-uk.svg' %}" alt="flag" width="14" height="14" data-uk-img>English</a></li>
									<li><a href="#"><img src="{% static 'home/img/in-lazy.gif' %}" data-src="{% static 'home/img/in-flag-id.svg' %}" alt="flag" width="14" height="14" data-uk-img>Indonesia</a></li>
								</ul>
							</div>
							<a href="{% url 'accounts:signin' %}" class="uk-button">Login</a>
						</div>
						<div>
							<h2 class="in-header-phone">1-800-123-4567</h2>
						</div>
					</div>
				</div>
				<hr>
			</div>
			<nav class="uk-navbar-container" data-uk-sticky="show-on-up: true; animation: uk-animation-slide-top;">
				<div class="uk-container" data-uk-navbar>
					<div class="uk-navbar-left uk-visible@m">
						<ul class="uk-navbar-nav">
							<li><a href="{% url 'home' %}">Home</a>
								
							</li>
							<li><a href="{% url 'markets' %}">Markets</a>
							</li>
							<li><a href="#">Company<span data-uk-navbar-parent-icon></span></a>
								<div class="uk-navbar-dropdown">
									<ul class="uk-nav uk-navbar-dropdown-nav">
										<li><a href="{% url 'about' %}">About</a></li>
										<li><a href="{% url 'blog' %}">Blog</a></li>
										<li><a href="{% url 'partners' %}">Partners</a></li>
										<li><a href="{% url 'contact' %}">Contact</a></li>
									</ul>
								</div>
							</li>
							<li><a href="{% url 'legal' %}">Term & conditions</a></li>
							<li><a href="{% url 'accounts:signin' %}">Login</a></li>
							<li><a href="{% url 'accounts:signup' %}">Create account</a></li>
							
							
						</ul>
					</div>
					<div class="uk-navbar-right" data-logo-inverse="filename: header-logo-uKXeo9.svg; width: 70; height: 70; inject: true">
						<div class="uk-navbar-item in-optional-nav">
							
						</div>
					</div>
				</div>
			</nav>
		</div>
	</header>
	<!-- header end -->
	{% block bodycontent %}

	{% endblock %}

	<!-- footer begin -->
	<footer>
		<div class="uk-section uk-section-secondary uk-light uk-margin-medium-top uk-background-contain uk-background-bottom-left" style="background-image: url({% static 'home/img/in-footer-background.png' %});">
			<div class="uk-container uk-margin-top">
				<div class="uk-grid" data-uk-grid="">
					<div class="uk-width-1-1 uk-width-expand@m">
						
							
					</div>
					<div class="uk-width-1-1 uk-width-auto@m">
						<div class="uk-flex uk-flex-left uk-flex-right@m">
							<!-- social media begin -->
							<div class="uk-flex social-media-list">
								<div><a href="https://www.facebook.com/indonez" class="color-facebook text-decoration-none"><i class="fab fa-facebook-square"></i> Facebook</a></div>
								<div><a href="https://twitter.com/indonez_tw" class="color-twitter text-decoration-none"><i class="fab fa-twitter"></i> Twitter</a></div>
								<div><a href="https://www.instagram.com/indonez_ig" class="color-instagram text-decoration-none"><i class="fab fa-instagram"></i> Instagram</a></div>
								<div><a href="#some-link" class="color-youtube text-decoration-none"><i class="fab fa-youtube"></i> Youtube</a></div>
							</div>
							<!-- social media end -->
						</div>
						<div class="uk-flex uk-flex-left uk-flex-right@m uk-margin-top">
							<div>
								<a href="#"><img src="{% static 'home/img/in-store-apple.png' %}" alt="download-app" width="134" height="39"></a>
								<a class="uk-margin-small-left" href="#"><img src="{% static 'home/img/in-store-google.png' %}" alt="download-app" width="133" height="39"></a>
							</div>
						</div>
					</div>
				</div>
				<div class="uk-grid uk-margin-large-top uk-margin-bottom">
					<div class="uk-width-1-1">
						<div class="footer-logo">
							<img class="uk-margin-small-right in-offset-top-10 uk-display-block" src="{% static 'home/img/user/footer-logo-YoUO7x.svg' %}" alt="footer-logo" width="110" height="39" data-uk-img="">
						</div>
						<p class="uk-heading-line uk-margin-medium-bottom copyright-text"><span>Copyright ©2022 marinasaving Capital Corporation. All Rights Reserved.</span></p>
						<p class="in-trading-risk">marinasaving Capital Advisors Corporation is an investment advisor registered with the Securities and Exchange Commission ("SEC"). Any reference to the advisory services refers to marinasaving Capital Advisors Corporation. Registration does not imply a certain level of skill or training nor does it imply endorsement by the SEC.​ Past performance is not a guarantee of future return, nor is it necessarily indicative of future performance. Keep in mind investing involves risk.</p>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<script src="//code.tidio.co/o5gi8rqlnknebabl6llmkfkf0efs9m8e.js" async></script>
	<!-- footer end -->
	<!-- to top begin -->
	<a href="#" class="to-top uk-visible@m" data-uk-scroll>
		Top<i class="fas fa-chevron-up" ></i>
	</a>
	<!-- to top end -->
	<!-- javascript -->
	<script src="{% static 'home/js/vendors/peity-vanilla.min.js' %}"></script>
	<script src="{% static 'home/js/config-peity.js' %}"></script>
	<script src="{% static 'home/js/utilities.min.js' %}"></script>
	<script src="{% static 'home/js/config-theme.js' %}"></script>
	{% block scriptcontent %}

	{% endblock %}
</body>

</html>

templates/markets.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
Our we invest your money
{% endblock %}

{% block bodycontent%}
	<main>
		<!-- section content begin -->
		<div class="uk-section">
			<div class="uk-container">
				<div class="uk-grid-match uk-grid-medium uk-child-width-1-2@s uk-child-width-1-3@m in-card-10" data-uk-grid>
					<div class="uk-width-1-1">
						<h1 class="uk-margin-remove-top uk-margin-small-bottom">A relationship on your terms.</h1>
						<h3 class="uk-text-light uk-margin-remove">Work with us the way you want.</h3>
						<p class="uk-text-lead uk-text-muted uk-margin-small-bottom">Some believe you must choose between an online broker and a wealth management firm. Whether you invest on your own, with an advisor, or a little of both — we can support you.</p>
					</div>
					<div>
						<div class="uk-card uk-card-default uk-card-body uk-box-shadow-small uk-border-rounded uk-light in-card-green">
							<div class="in-icon-wrap circle uk-margin-medium-bottom">
								<i class="fas fa-seedling fa-lg"></i>
							</div>
							<h4 class="uk-margin-top">
								<a href="#">Investing</a>
							</h4>
							<hr>
							<p>A wide selection of investment product to help build diversified portfolio</p>
						</div>
					</div>
					<div>
						<div class="uk-card uk-card-default uk-card-body uk-box-shadow-small uk-border-rounded uk-light in-card-blue">
							<div class="in-icon-wrap circle uk-margin-medium-bottom">
								<i class="fas fa-chart-bar fa-lg"></i>
							</div>
							<h4 class="uk-margin-top">
								<a href="#">Trading</a>
							</h4>
							<hr>
							<p>Powerful trading tools, resources, insight and support</p>
						</div>
					</div>
					<div>
						<div class="uk-card uk-card-default uk-card-body uk-box-shadow-small uk-border-rounded uk-light in-card-purple">
							<div class="in-icon-wrap circle uk-margin-medium-bottom">
								<i class="fas fa-chart-pie fa-lg"></i>
							</div>
							<h4 class="uk-margin-top">
								<a href="#">Wealth management</a>
							</h4>
							<hr>
							<p>Dedicated financial consultant to help reach your own specific goals</p>
						</div>
					</div>
					<div>
						<div class="uk-card uk-card-default uk-card-body uk-box-shadow-small uk-border-rounded uk-light in-card-navy">
							<div class="in-icon-wrap circle uk-margin-medium-bottom">
								<i class="fas fa-chalkboard-teacher fa-lg"></i>
							</div>
							<h4 class="uk-margin-top">
								<a href="#">Investment advisory</a>
							</h4>
							<hr>
							<p>A wide selection of investing strategies from seasoned portfolio managers</p>
						</div>
					</div>
					<div>
						<div class="uk-card uk-card-default uk-card-body uk-box-shadow-small uk-border-rounded uk-light in-card-grey">
							<div class="in-icon-wrap circle uk-margin-medium-bottom">
								<i class="fas fa-funnel-dollar fa-lg"></i>
							</div>
							<h4 class="uk-margin-top">
								<a href="#">Smart portfolio</a>
							</h4>
							<hr>
							<p>A revolutionary, fully-automated investmend advisory services</p>
						</div>
					</div>
					<div>
						<div class="uk-card uk-card-default uk-card-body uk-box-shadow-small uk-border-rounded uk-light in-card-orange">
							<div class="in-icon-wrap circle uk-margin-medium-bottom">
								<i class="fas fa-handshake fa-lg"></i>
							</div>
							<h4 class="uk-margin-top">
								<a href="#">Mutual fund advisor</a>
							</h4>
							<hr>
							<p>Specialized guidance from independent local advisor for hight-net-worth investors</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- section content end -->
		<!-- section content begin -->
		<div class="uk-section in-offset-top-20 in-offset-bottom-20">
			<div class="uk-container">
				<div class="uk-grid">
					<div class="uk-width-2-3@m">
						<div class="uk-grid uk-grid-small" data-uk-grid>
							<div class="uk-width-auto@m">
								<div class="in-icon-wrap circle large primary-color uk-margin-right">
									<i class="fas fa-money-bill-wave fa-2x"></i>
								</div>
							</div>
							<div class="uk-width-expand">
								<h3>Why trade with Fina Capital?</h3>
								<p>Let's go right back to basics. The goal of fina capital (also called "FC" or "fina"), like any investment strategy, is to increase the value of invested capital.

									FCs make returns by investing into lots of early stage startups that have a small chance of being really enormously successful.
									
									They're the people that invested in companies like Facebook, Uber, and Airbnb, before they got big. By investing in early-stage companies, FCs drive innovation.</p>
								<div class="uk-grid uk-child-width-1-1 uk-child-width-1-2@m">
									<div>
										<ul class="uk-list in-list-check">
											<li>Direct Market Access (DMA)</li>
											<li>Leverage up to 1:500</li>
											<li>T+0 settlement</li>
											<li>Dividends paid in cash</li>
										</ul>
									</div>
									<div class="in-margin-top-10@s in-margin-bottom-30@s">
										<ul class="uk-list in-list-check">
											<li>Free from UK Stamp Duty</li>
											<li>Short selling available</li>
											<li>Commissions from 0.08%</li>
											<li>Access to 1500 global shares</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="uk-width-1-3@m">
						<h3>Our Shares in</h3>
						<table class="uk-table uk-table-divider uk-table-striped uk-text-small uk-text-center">
							<thead>
								<tr>
									<th class="uk-text-center">Name</th>
									<th class="uk-text-center">Share</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Apple Inc CFD</td>
									<td>10%</td>
								</tr>
								<tr>
									<td>Alibaba CFD</td>
									<td>17%</td>
								</tr>
								<tr>
									<td>Facebook CFD</td>
									<td>9%</td>
								</tr>
								<tr>
									<td>Tesla TSL</td>
									<td>11%</td>
								</tr>
								<tr>
									<td>Amazon AZN</td>
									<td>10%</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<!-- section content end -->
		<!-- section content begin -->
		<div class="uk-section">
			<div class="uk-container">
				<div class="uk-grid">
					<div class="uk-width-1-1 in-card-16">
						<div class="uk-card uk-card-default uk-card-body uk-border-rounded">
							<div class="uk-grid uk-flex-middle" data-uk-grid>
								<div class="uk-width-1-1 uk-width-expand@m">
									<h3>Deposit up to $600 plus and get 60 days of commission-free stocks & $1000 </h3>
								</div>
								<div class="uk-width-auto">
									<a class="uk-button uk-button-primary uk-border-rounded" href="{% url 'accounts:signup' %}">Open an Account</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- section content end -->
	</main>
	{% endblock %}